# comprehensive github action yml reference: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: esclusive_ai_for_github_repo

on:
  workflow_call:

permissions:
  contents: write # need this permission to publish knowledge base to GitHub Release

jobs:
  esclusive_repo_ai:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3" # https://github.com/marketplace/actions/checkout
      - uses: "actions/setup-python@v4" # https://github.com/marketplace/actions/setup-python
        with:
          python-version: "3.11"
      - name: "build and publish all in one knowledge base"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xe
          mkdir -p tmp
          curl -fsSL https://github.com/easyscalecloud/esclusive-ai-for-github-repo/releases/download/0.1.1/esclusive_ai_for_github_repo.py -o tmp/esclusive_ai_for_github_repo.py
          curl -fsSL https://github.com/easyscalecloud/esclusive-ai-for-github-repo/releases/download/0.1.1/requirements.txt -o tmp/requirements.txt
          curl -fsSL https://github.com/easyscalecloud/esclusive-ai-for-github-repo/releases/download/0.1.1/prompt.md -o tmp/prompt.md
          pip3 install -r tmp/requirements.txt
          python3 tmp/esclusive_ai_for_github_repo.py
